Component ID	      Component Name
RPI	Raspberry       Pi Zero 2 W
L298N	              Motor Driver - L298N
M1	                N20 Motor 1 - N20 DC 3v 30 Rpm
M2	                N20 Motor 2 - N20 DC 3v 30 Rpm 
BATT	              3.7V Rechargeable Battery - EEMB LiPO 3.7v 1100mAh 903042
USB	                USB Charging Port TP4056
US	                Ultrasonic Ranger - HC-SR04
IR_L	              Left IR Tracking Sensor - TCRT5000
IR_R	              Right IR Tracking Sensor - TCRT5000
IR_REAR	            Rear IR Obstacle Detection Sensor - KY032
TOUCH	              TTP223B Capacitive Touch Sensor - TTP223B
CAM	                piCamera Module - OV5647

Additional ID       Component Name
MB                  Microbit v1
Amp                 amplifyer MAX98357
Speaker             3mm x 25mm x 6.8mm side sound 4Ohm 2 Watt speaker
mic                 Omnidirectional Mic - INMP441
Servo's             9g Servomotor SG90
Cable's             1mm soft flexi cable
PW Cable's          1.5mm cable
